id: I45CA9DB4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-13T19:17:35+00:00'
last_modified: '2022-06-15T16:41:03.582460+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27883
  title: རྒྱུད་སྡེ་ཀུན་བཏུས། （གློག་ཀླད་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9AE9:
      image_group_id: I4649
      title: ''
      total_pages: 850
      order: 1
      base_file: 9AE9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
