id: opecha:P000337
initial_creation_type: ocr
source_metadata:
  id: bdr:W27883
  title: རྒྱུད་སྡེ་ཀུན་བཏུས། （གློག་ཀླད་པར་མ།）
  volume:
    a2e92e779f844454843fb23a57b9d273:
      image_group_id: I4649
      title: ''
      volume_number: 1
      total_pages: 850
    6c31db78df44403f84a2e1eafe00125a:
      image_group_id: I4650
      title: ''
      volume_number: 2
      total_pages: 698
    68e66d6092ec47ac818bb337ad0a5e41:
      image_group_id: I4651
      title: ''
      volume_number: 3
      total_pages: 736
    db3e2aae31f44dd494b235dd2284b1b7:
      image_group_id: I4652
      title: ''
      volume_number: 4
      total_pages: 602
    9af030072bfc489eb8f87f389a34fe4d:
      image_group_id: I4653
      title: ''
      volume_number: 5
      total_pages: 826
    931bf5d09c914a56986fe4651cc27ccd:
      image_group_id: I4654
      title: ''
      volume_number: 6
      total_pages: 784
    8d446f50d7d64443913dbea66c1356e4:
      image_group_id: I4655
      title: ''
      volume_number: 7
      total_pages: 834
    d9eb9e63fd1546acaec83ed8380af110:
      image_group_id: I4656
      title: ''
      volume_number: 8
      total_pages: 794
    ea164a4d46104ad79892bcdaab9709ef:
      image_group_id: I4657
      title: ''
      volume_number: 9
      total_pages: 696
    0acc91a9ede243f5b81587af3269c297:
      image_group_id: I4658
      title: ''
      volume_number: 10
      total_pages: 816
    b531856f38ac475d82b2eb401db18922:
      image_group_id: I4659
      title: ''
      volume_number: 11
      total_pages: 718
    1446f608a99f4d099f9fa8f6f6390b47:
      image_group_id: I4660
      title: ''
      volume_number: 12
      total_pages: 610
    12e83030697f447db5db991c3ea24190:
      image_group_id: I4661
      title: ''
      volume_number: 13
      total_pages: 682
    985373edf57048f3ad26448c3f128a60:
      image_group_id: I4662
      title: ''
      volume_number: 14
      total_pages: 706
    b0e8b160fd694f7b8372634dd99a0b2e:
      image_group_id: I4663
      title: ''
      volume_number: 15
      total_pages: 686
    8c6047c22a724c56b7d12a6d88b42ed9:
      image_group_id: I4664
      title: ''
      volume_number: 16
      total_pages: 752
    4355e9cbe5d7429289dd3d9599930406:
      image_group_id: I4665
      title: ''
      volume_number: 17
      total_pages: 812
    b0f35b12e451435cbf6f0b308287bc26:
      image_group_id: I4666
      title: ''
      volume_number: 18
      total_pages: 702
    e4f2e37caeb44803bb53fc76bbe104a8:
      image_group_id: I4667
      title: ''
      volume_number: 19
      total_pages: 690
    fc39e3dc544f40b3b52c53f2665ec7bf:
      image_group_id: I4668
      title: ''
      volume_number: 20
      total_pages: 784
    ecb1ee7763f34cf0b589fa56b4bf7592:
      image_group_id: I4669
      title: ''
      volume_number: 21
      total_pages: 834
    88b985ecd2a3425aa69175d7e99b07fe:
      image_group_id: I4670
      title: ''
      volume_number: 22
      total_pages: 776
    ee03604f95d5449aa67cd318ec07e412:
      image_group_id: I4671
      title: ''
      volume_number: 23
      total_pages: 916
    58f0cfd07a104f4aa80b81c4fd4761f2:
      image_group_id: I4672
      title: ''
      volume_number: 24
      total_pages: 654
    376543196fa349c5b171dadcc4452d56:
      image_group_id: I4673
      title: ''
      volume_number: 25
      total_pages: 664
    10693efcee9a48199f3a359f7c52d372:
      image_group_id: I4674
      title: ''
      volume_number: 26
      total_pages: 670
    e2661f1f6b7c4d23a78b967473f373c5:
      image_group_id: I4675
      title: ''
      volume_number: 27
      total_pages: 700
    38c32eb9de0f45fb85a1300dac8993ba:
      image_group_id: I4676
      title: ''
      volume_number: 28
      total_pages: 672
    57411558d85941dcba59a913839bfc49:
      image_group_id: I4677
      title: ''
      volume_number: 29
      total_pages: 730
    0d08702bfef64f22b9ee9e0ad5e06523:
      image_group_id: I4678
      title: ''
      volume_number: 30
      total_pages: 688
    91c8cab5ce3d48b79fdd99d66de969b7:
      image_group_id: I4679
      title: ''
      volume_number: 31
      total_pages: 612
    e4bcdc4933e147dfa9afbeafc245d712:
      image_group_id: I4680
      title: ''
      volume_number: 32
      total_pages: 918
  author: ''
ebook_metadata:
  title: རྒྱུད་སྡེ་ཀུན་བཏུས། （གློག་ཀླད་པར་མ།）
  author: ''
  sku: P000337
  cover: cover.jpg
  layers:
  - pagination
